import { ReactNode, Suspense } from "react";
import type { Metadata } from "next";
import "./styles/globals.scss";
import { arno, pxGrotesk } from "./fonts";
import MenuIcon from "./components/icons/menu";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Scorci",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <header className={styles["header-container"]}>
            <div className={styles["header-menu-container"]}>
              <MenuIcon className={styles["header-menu-icon"]} />
            </div>
            <div className={styles["header-title-container"]}>
              <p className={`${arno.className} ${styles["header-title"]}`}>
                Scorci
              </p>
            </div>
            <nav className={styles["header-nav-container"]}>
              <ul className={`${pxGrotesk.className} ${styles["header-nav-list"]}`}>
                <li>Artists</li>
                <span className={styles["header-nav-list-separator"]}>/</span>
                <li>Gallery</li>
              </ul>
            </nav>
          </header>
          <main>{children}</main>
        </Suspense>
      </body>
    </html>
  );
}
